services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Skynettechnologies\Allinoneaccessibilitymonitor\:
    resource: '../Classes/*'

  Skynettechnologies\Allinoneaccessibilitymonitor\Property\TypeConverter\UploadedFileReferenceConverter:
    tags:
      - name: extbase.type_converter
        priority: 33
        target: TYPO3\CMS\Extbase\Domain\Model\FileReference
        sources: array

  Skynettechnologies\Allinoneaccessibilitymonitor\Property\TypeConverter\ObjectStorageConverter:
    tags:
      - name: extbase.type_converter
        priority: 23
        target: TYPO3\CMS\Extbase\Persistence\ObjectStorage
        sources: array
